### ISSUE TITLE
admin-points-4326.zip is no longer available

### ISSUE THREAD

**Issue by MichaelKreil** [shortbread-tiles/shortbread-tilemaker#34]
The file at "https://shortbread-tiles.org/shapefiles/admin-points-4326.zip" (referenced in [get-shapefiles.sh](https://github.com/shortbread-tiles/shortbread-tilemaker/blob/3240a64592ab177952d03579582da5799ff77343/get-shapefiles.sh#L31)) is no longer available.
@Nakaner, do you have the script that generates this file?

**Comment by astridx** [comment]
Is this perhaps the file created with these [instructions](https://github.com/shortbread-tiles/shortbread-tilemaker/blob/main/boundary_labels_shape_file.md)?

**Comment by Nakaner** [comment]
> Is this perhaps the file created with these [instructions](https://github.com/shortbread-tiles/shortbread-tilemaker/blob/main/boundary_labels_shape_file.md)?

Yes, these are the instructions.

I made the shape file temporarily available at https://shortbread.geofabrik.de/shapefiles/admin-points-4326.zip
